# Generated by Django 5.0.6 on 2024-06-29 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0006_alter_product_price_alter_product_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('estado', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('nombre', models.CharField(default=None, max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='estado',
            field=models.ForeignKey(default='A', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Products.estado'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='estado',
            field=models.ForeignKey(default='A', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Products.estado'),
        ),
        migrations.AddField(
            model_name='product',
            name='estado',
            field=models.ForeignKey(default='A', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Products.estado'),
        ),
    ]
