# Generated by Django 5.0.6 on 2024-06-29 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0007_estado_category_estado_customuser_estado_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estado',
            old_name='estado',
            new_name='simbolo',
        ),
    ]
